I never actually generated a UUID and I went with KAFKA_KRAFT_CLUSTER_ID=cluster-12345 in docker-compose.yml
Now it's a good time to actually generate a UUID?

sudo docker run --rm bitnami/kafka:latest kafka-storage random-uuid

kafka 18:53:22.31 INFO  ==> Welcome to the Bitnami kafka container
kafka 18:53:22.31 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 18:53:22.31 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.

/opt/bitnami/scripts/kafka/entrypoint.sh: line 29: exec: kafka-storage: not found
----------------
You’re fine to keep using KAFKA_KRAFT_CLUSTER_ID=cluster-12345

Updated docker-compose.yml with
KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.9:9092

* restart Kafka:
sudo docker compose down
 ✔ Container kafka      Removed                                                                                                                                                         1.1s
 ✔ Network kfk_default  Removed                                                                                                                                                         0.4s
 
sudo docker compose up -d
 ✔ Network kfk_default  Created                                                                                                                                                         0.0s
 ✔ Container kafka      Started                                                                                                                                                         0.2s

* Make sure Kafka is up
sudo docker ps -a|grep kafka

* try running your Python consumer again
* try running your Python producer again
%3|1743794208.343|FAIL|rdkafka#producer-1| [thrd:192.168.0.9:9092/bootstrap]: 192.168.0.9:9092/bootstrap: Connect to ipv4#192.168.0.9:9092 failed: Unknown error (after 2065ms in state CONNECT)

* log
kafka 19:16:00.40 ERROR ==> Role 'controller' enabled but listener CONTROLLER not found in KAFKA_CFG_LISTENERS.
/opt/bitnami/scripts/libkafka.sh: line 401: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: unbound variable
kafka 19:16:00.41 WARN  ==> Kafka has been configured with a PLAINTEXT listener, this setting is not recommended for production environments.

